Output oauth2-demo.gif
Set Shell bash
Set Width 1200
Set Height 800
Set FontSize 28
Set Theme Dracula
Set WindowBar Colorful

Sleep 1s

# Move to project directory
Type "cd /c/Users/hp/Downloads/spring-boot-oauth2-login-template/spring-boot-oauth2-login-template"
Enter
Sleep 1s

# Start Spring Boot app
Type "mvn spring-boot:run"
Enter

Sleep 8s

# Stop the server (just press Ctrl+C)
Ctrl+C
Sleep 1s
